AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "active-admin-vpn-auto-login.gemspec"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
